Imported Debian patch 2.30-4

diff --git a/debian/spampd.init b/debian/spampd.init
--- a/debian/spampd.init
+++ b/debian/spampd.init
@@ -33,7 +33,8 @@ GRPID=spampd
 
 if [ "$EUID" !=  "0" ]; then
 	echo "ERROR: Insufficient privileges. Retry as root" >&2
-	exit 1
+	# LSB 3.0 says that return value of 4 indicates insufficient privileges
+	exit 4
 fi
 
 if [ -f /etc/default/$NAME ]; then
@@ -122,7 +123,7 @@ case "$1" in
 	start)
 		if ! istrue "${STARTSPAMPD}"; then
 			echo "Starting $DESC: $NAME (disabled in /etc/default/$NAME)."
-			# returncode 5 demanded for this case by LSB 2.1
+			# LSB 2.1: 6 mean unconfigured. This seems appropriate here.
 			exit 6
 		fi
 		echo -n "Starting $DESC: $NAME"
